inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i':    '()'
    '%w':    '()'

Layout/LineLength:
  Max: 263

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/fiskaly-ruby.rb'

Lint/MissingSuper:
  Exclude:
    - 'lib/**/*authenticate.rb'

Style/StringLiteralsInInterpolation:
  Enabled: false
